// <auto-generated />
namespace MarkdownApi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201609211350156_add-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
